version: "3.8"

services:
  traffix_ui:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    env_file:
      - .env
    networks:
      - redis
      - caddy
    labels:
      caddy: traffix.veesix-networks.co.uk
      caddy.reverse_proxy: "{{upstreams 80}}"

  traffix_worker:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.worker
    env_file:
      - .env
    networks:
      - redis
    depends_on:
      - redis

  traffix_notifier:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.notifier
    env_file:
      - .env
    networks:
      - redis
    depends_on:
      - redis
      - traffix_worker

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    
  redis:
    image: bitnami/redis:7.2.4
    networks:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    ports:
      - 6379:6379
    restart: unless-stopped

networks:
  caddy:
    external: true
  redis:

volumes:
  caddy_data: {}