name: New Game Update
description: Add a new Game Update Event to the database to be approved by the community / an administrator
title: "[GAME_UPDATE]: "
labels: ["event_game_update"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the Game
      placeholder: Harry Plopper and the Gang of Bandits
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Version of the Update
      placeholder: v1.4.33+r1
    validations:
      required: true
  - type: input
    id: size
    attributes:
      label: Size
      description: Estimated size of Update in Gigabytes
      placeholder: "13"
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: Estimated Date of release
      placeholder: 01/01/1990
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: Source of update and estimated size
      placeholder: https://some-cool-website.com/release-of-harry-plopper-update-v1.4.33+r1
    validations:
      required: true