sidebar_menu = [
    {"text": "Navigation", "is_header": 1},
    {"url": "/", "icon": "bi bi-cpu", "text": "Home", "name": "index"},
    {
        "url": "/game_releases",
        "text": "Game Releases",
        "icon": "bi bi-collection",
        "name": "game_releases",
    },
    {
        "url": "/game_updates",
        "text": "Game Updates",
        "icon": "bi bi-columns-gap",
        "name": "game_updates",
    },
    {
        "url": "#",
        "text": "Sport Events",
        "icon": "bi bi-trophy",
        "name": "sport_events",
        "disabled": True,
    },
    {
        "url": "#",
        "text": "Social Events",
        "icon": "bi bi-person-bounding-box",
        "name": "social_events",
        "disabled": True,
    },
    {
        "url": "#",
        "text": "New Films / Series",
        "icon": "bi bi-camera-reels",
        "name": "films_and_series",
        "disabled": True,
    },
    {
        "url": "https://github.com/veesix-networks/traffix/issues/new/choose",
        "text": "Create Request",
        "icon": "bi bi-pen",
        "name": None,
        "target": "_blank",
    },
    {
        "url": "#",
        "text": "About",
        "icon": "bi bi-people",
        "name": "about",
        "disabled": True,
    },
]
